---
apiVersion: v1
kind: Service
metadata:
  name: svc1
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: argo-svc 
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: svc1
  namespace: argocdlab4
spec:
  type: ClusterIP
  selector:
    app: argo-svc 
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
