---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager
  namespace: argocd
spec:
  project: mmaproject1
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.13.2
    helm:
      releaseName: cert-manager
  destination:
    server: "https://kubernetes.default.svc"
    namespace: certmanager
